import { constants } from 'node:fs'
import { access, chmod, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { findTopLevelSections, storeChangelogEntry } from '../../changelog'

const releaseUrl = 'https://github.com/owner/repo/releases/tag/v1.2.3'
const entry = `# v1.2.3 (2026-08-03T00:00:00.000Z)

This changelog is generated by [GitHub Releases](${releaseUrl})

## Changes

- generated

`

let directory: string
let output: string

beforeEach(async () => {
  directory = await mkdtemp(join(tmpdir(), 'gh-changelogen-store-'))
  output = join(directory, 'CHANGELOG.md')
})

afterEach(async () => {
  await rm(directory, { force: true, recursive: true })
})

test('creates a new changelog', async () => {
  await expect(storeChangelogEntry({ entry, output, releaseUrl })).resolves.toBe('created')
  expect(await readFile(output, 'utf8')).toBe(`${entry}\n`)
})

test('prepends an entry without changing existing bytes', async () => {
  const existing = '# v1.0.0 (old)\n\nold body without a final newline'
  await writeFile(output, existing)

  await expect(storeChangelogEntry({ entry, output, releaseUrl })).resolves.toBe('prepended')
  expect(await readFile(output, 'utf8')).toBe(`${entry}\n${existing}`)
})

test('prepends a stable entry without replacing its prerelease section', async () => {
  const stableReleaseUrl = 'https://github.com/owner/repo/releases/tag/v0.1.0'
  const stableEntry = `# v0.1.0 (2026-08-08T12:00:00.000Z)

This changelog is generated by [GitHub Releases](${stableReleaseUrl})
`
  const prereleaseUrl = `${stableReleaseUrl}-beta.0`
  const prereleaseEntry = `# v0.1.0-beta.0 (2026-08-08T11:26:28.023Z)

This changelog is generated by [GitHub Releases](${prereleaseUrl})
`
  await writeFile(output, prereleaseEntry)

  await expect(
    storeChangelogEntry({ entry: stableEntry, output, releaseUrl: stableReleaseUrl })
  ).resolves.toBe('prepended')
  expect(await readFile(output, 'utf8')).toBe(`${stableEntry}\n${prereleaseEntry}`)
})

test('prepends before an existing preamble when no top-level section matches', async () => {
  const existing = 'Changelog preamble\n\n## Nested heading\n'
  await writeFile(output, existing)

  await storeChangelogEntry({ entry, output, releaseUrl })
  expect(await readFile(output, 'utf8')).toBe(`${entry}\n${existing}`)
})

test('replaces only the matching CRLF section', async () => {
  const preamble = 'Preamble bytes\r\n\r\n'
  const target = [
    '# v1.2.3 (old)',
    '',
    `This changelog is generated by [GitHub Releases](${releaseUrl})`,
    '',
    'old body',
    ''
  ].join('\r\n')
  const unrelated = '# v1.0.0 (old)\r\n\r\nUnrelated  \r\nbytes'
  await writeFile(output, `${preamble}${target}${unrelated}`)

  await expect(storeChangelogEntry({ entry, output, releaseUrl })).resolves.toBe('replaced')
  expect(await readFile(output, 'utf8')).toBe(
    `${preamble}${entry.replaceAll('\n', '\r\n')}\r\n${unrelated}`
  )
})

test('does not write or rename when content is unchanged', async () => {
  await storeChangelogEntry({ entry, output, releaseUrl })

  await expect(
    storeChangelogEntry(
      { entry, output, releaseUrl },
      {
        rename: async () => {
          throw new Error('rename should not run')
        }
      }
    )
  ).resolves.toBe('unchanged')
})

test('rejects duplicate matching sections without changing the file', async () => {
  const section = `${entry}\n`
  const existing = `${section}${section}`
  await writeFile(output, existing)

  await expect(storeChangelogEntry({ entry, output, releaseUrl })).rejects.toThrow(
    'Multiple CHANGELOG sections found'
  )
  expect(await readFile(output, 'utf8')).toBe(existing)
})

test('preserves the existing file mode', async () => {
  if (process.platform === 'win32') {
    return
  }

  await writeFile(output, '# old\n')
  await chmod(output, 0o640)
  await storeChangelogEntry({ entry, output, releaseUrl })

  expect((await stat(output)).mode & 0o777).toBe(0o640)
})

test('fails clearly when the output directory does not exist', async () => {
  const missingOutput = join(directory, 'missing', 'CHANGELOG.md')
  await expect(storeChangelogEntry({ entry, output: missingOutput, releaseUrl })).rejects.toThrow(
    'Output directory does not exist'
  )
})

test('fails clearly when the output parent is not a directory', async () => {
  const parentFile = join(directory, 'not-a-directory')
  await writeFile(parentFile, 'file')

  await expect(
    storeChangelogEntry({ entry, output: join(parentFile, 'CHANGELOG.md'), releaseUrl })
  ).rejects.toThrow(/not a directory|ENOTDIR/i)
})

test('keeps the original file and cleans up after rename failure', async () => {
  const existing = '# old\n\nunchanged\n'
  const temporaryPath = join(directory, '.CHANGELOG.test.tmp')
  await writeFile(output, existing)

  await expect(
    storeChangelogEntry(
      { entry, output, releaseUrl },
      {
        createTemporaryPath: () => temporaryPath,
        rename: async () => {
          throw new Error('rename failed')
        }
      }
    )
  ).rejects.toThrow('rename failed')

  expect(await readFile(output, 'utf8')).toBe(existing)
  await expect(access(temporaryPath, constants.F_OK)).rejects.toMatchObject({ code: 'ENOENT' })
})

test('does not remove a pre-existing temporary-path collision', async () => {
  const temporaryPath = join(directory, '.CHANGELOG.collision.tmp')
  await writeFile(temporaryPath, 'belongs to someone else')

  await expect(
    storeChangelogEntry({ entry, output, releaseUrl }, { createTemporaryPath: () => temporaryPath })
  ).rejects.toMatchObject({ code: 'EEXIST' })
  expect(await readFile(temporaryPath, 'utf8')).toBe('belongs to someone else')
})

test('finds only top-level Markdown headings', () => {
  const content = 'preamble\n## nested\n# first\nbody\n### nested\n# second\n'
  const sections = findTopLevelSections(content)

  expect(sections).toEqual([
    { start: content.indexOf('# first'), end: content.indexOf('# second') },
    { start: content.indexOf('# second'), end: content.length }
  ])
})
