- name: feature
  description: Includes new features
  color: 'ffff00'
- name: bug
  description: Includes new features
  color: 'ee0701'
- name: improvement
  description: Includes backwards-compatible fixes
  color: '1d76db'
- name: breaking
  description: Includes backwards-incompatible fixes
  color: 'b60205'
- name: refactoring
  description: A code change that neither fixes a bug nor adds a feature
  color: 'fbca04'
- name: security
  description: Security fixes
  color: 'b60205'
- name: documentation
  description: Includes documetation fixes
  color: '5319e7'
- name: example
  description: Includes example and demo code fixes
  color: 'db0875'
- name: deprecated
  description: Includes deprecate fixes
  color: 'f7ffa8'
- name: performance
  description: Includes performance fixes
  color: 'cc317c'
- name: i18n
  description: Includes internationalization fixes
  color: 'ffd412'
- name: a11y
  description: Inlucdes accessibility fixes
  color: '0000ff'
- name: dependency
  description: Includes dependency fixes
  color: 'ffbce7'
- name: todo
  description: todo tasks
  color: 'c2e0c6'
- name: duplicate
  description: This issue or Pull Request already exists
  color: 'ededed'
- name: help wanted
  description: Extra attention is needed
  color: 'e99695'
- name: good first issue
  description: Good for newcomers
  color: '7057ff'
- name: 'status: abandoned'
  description: The issue or Pull Request is wontfix
  color: '000000'
- name: 'status: blocked'
  description: Progress on the issue is Blocked
  color: 'ee0701'
- name: 'status: in progress'
  description: Work in Progress
  color: 'cccccc'
- name: 'status: proposal'
  description: Request for comments
  color: 'd4c5f9'
- name: 'status: pull request welcome'
  description: Welcome to Pull Request
  color: '2E7733'
- name: 'status: review needed'
  description: Request for review
  color: 'fbca04'
- name: 'status: need more repro codes or info'
  description: Lacks enough info to make progress
  color: 'F9C90A'
