catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
allowBuilds:
  '@nexhome/yorkie': set this to true or false
  esbuild: true
  unrs-resolver: true
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    '@types/node': '*'
    vite: '*'
