import { isFunction } from './utils'

import type { GitHubRelease, Generator } from './types'

function generatorDefault(release: GitHubRelease): Promise<string> {
  console.log('generatorDefault', release)
  // prettier-ignore
  return Promise.resolve(`# ${release.name}${release.name !== release.tag_name ? ` ${release.tag_name}` : ''} (${release.published_at})

This changelog is generated by [GitHub Releases](${release.url})

${release.body}

`)
}

export async function generateChangelog(
  release: GitHubRelease,
  generator: Generator = generatorDefault
): Promise<string> {
  if (!isFunction(generator)) {
    throw new Error('generator is not a function')
  }
  return generator(release)
}
