import { isFunction } from './utils'

import type { GitHubRelease, Generator, ReleaseNotes } from './types'

export function renderChangelogEntry(notes: ReleaseNotes): string {
  const name = notes.name || notes.tagName
  // prettier-ignore
  return `# ${name}${name !== notes.tagName ? ` ${notes.tagName}` : ''} (${notes.timestamp})

This changelog is generated by [GitHub Releases](${notes.htmlUrl})

${notes.body}

`
}

function generatorDefault(release: GitHubRelease): Promise<string> {
  return Promise.resolve(
    renderChangelogEntry({
      body: release.body,
      htmlUrl: release.html_url,
      name: release.name || release.tag_name,
      repository: '',
      source: 'published-release',
      tagName: release.tag_name,
      timestamp: release.published_at
    })
  )
}

export async function generateChangelog(
  release: GitHubRelease,
  generator: Generator = generatorDefault
): Promise<string> {
  if (!isFunction(generator)) {
    throw new Error('generator is not a function')
  }
  return generator(release)
}
