name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Extract version tag
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref }}
          separator: '/'
      - name: Create Github Release
        run: gh release create ${{ steps.split.outputs._2 }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Genearte changelog
        run: |
          cat CHANGELOG.md | cat <(npx gh-changelogen --repo=kazupon/gh-changelogen --tag=${{ steps.split.outputs._2 }}) - > .temp.txt
          rm CHANGELOG.md
          mv .temp.txt CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          file_pattern: '*.md'
          commit_message: 'chore: sync changelog'
      - name: Publish
        run: ./scripts/release.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
