name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Extract version tag
        if: startsWith( github.ref, 'refs/tags/v' )
        run: echo ${{ github.ref }}
        env:
          REF: ${{ github.ref }}
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref }} --generate-notes
      - name: Wait
        run: |
          # Wait for the github release
          sleep 10
      - name: Genearte changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat CHANGELOG.md | cat <(gh release view --json createdAt,tagName,name,url,publishedAt,body --template \
          '# {{.name }}{{if ne .tagName .name }} {{.tagName}}{{ end }} ({{ .publishedAt }})

          This changelog is generated by [GitHub Releases]({{.url}})

          {{ .body }}

          ') - > .temp.txt
          rm CHANGELOG.md
          mv .temp.txt CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          file_pattern: '*.md'
          commit_message: 'release: ${{ github.ref }}'
      - name: Publish
        run: |
          npm publish
