name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Extract version tag
        if: startsWith( github.ref, 'refs/tags/v' )
        run: echo ${{ github.ref }}
        env:
          REF: ${{ github.ref }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref }}
          separator: '/'
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.split.outputs._2 }} --generate-notes
      - name: Wait
        run: |
          # Wait for the github release
          sleep 10
      - name: Genearte changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat CHANGELOG.md | cat <(gh release view ${{ steps.split.outputs._2 }} --json createdAt,tagName,name,url,publishedAt,body --template \
          '# {{.name }}{{if ne .tagName .name }} {{.tagName}}{{ end }} ({{ .publishedAt }})

          This changelog is generated by [GitHub Releases]({{.url}})

          {{ .body }}

          ') - > .temp.txt
          rm CHANGELOG.md
          mv .temp.txt CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          file_pattern: '*.md'
          commit_message: 'chore: generate changelog'
      - name: Publish
        run: ./scripts/release.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
