name: Test

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 16.x

      - name: Generate changelog
        run: |
          pnpm install --no-frozen-lockfile
          ./cli.mjs --repo=kazupon/gh-changelogen --tag=v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
